@startuml
'https://plantuml.com/class-diagram


package "Bases des objets" <<Frame>> {

    class Page {
        -title : String
        -author : String
        toHTML() : String
    }

    abstract class Tag {
        - text : String
        getText() : String
        setText(text : String) : void
        toHTML() : String
    }

    Tag <|-- Paragraph
    Tag <|-- Title
    Tag <|-- Link
    Tag <|-- Image

    Page -> "*" Tag : content
    Site -> "*" Page : pages

    class Site {
        -title : String
        -pages : Map<String, Page>
        add(Page p)
        remove(Page p)
        render(String name)
    }

    Image : toHTML(): String
    Link : toHTML(): String
    Title : toHTML(): String
    Paragraph : toHTML(): String

}

package "Composite - création de div dans des div" <<Frame>> {

    class Div2Col {

    }

    Tag <|--- Div2Col
    Tag "colA *" <-- Div2Col
    Tag "colB *" <-- Div2Col

    Div2Col : toHTML(): String

}

package "Decorator - ajout de style à tout Tag" <<Frame>> {

    abstract class StyleCSS
    Tag <|-- StyleCSS
    Tag <-- StyleCSS

    StyleCSS <|-- Colored
    StyleCSS <|-- Bolded
    StyleCSS <|-- Underligned

    Underligned : toHTML(): String
    Bolded : toHTML(): String
    Colored : toHTML(): String

}


package "Prototype - mise à dispo de templates" <<Frame>> {
    Page : clone()

    Registry --> "templates *" Page
    class Registry {
        add(String, Page)
        remove(String)
        get(String) : Page
    }

    Tag : <abstract> clone()
}

package "Builder - création 'simple' de templates" <<Frame>> {
      class PageBuilder {
        addParagraph()
        addLink()
        addTitle()
        addImage()
        build() : Page
      }

      PageBuilder ..> "<create>" Page
      PageBuilder -> Registry
      PageBuilder -> "inProgress" Page
}


package "Abstract factory" <<Frame>> {

    interface StyledTagFactory {
        createParagraph() : Paragraph
        createTitle(): Title
        createLink(): Link
        createImage(): Image
    }

    StyledTagFactory <|.. DraculaStyleFactory
    StyledTagFactory <|.. ModernStyleFactory
    StyledTagFactory <|.. SportStyleFactory

    class DraculaStyleFactory {
    createParagraph() : Paragraph
            createTitle(): Title
            createLink(): Link
            createImage(): Image
    }


     Colored <.. DraculaStyleFactory : "generates"
     Title <.. DraculaStyleFactory : "generates"

}

@enduml